### ISSUE TITLE
DB DATES 테이블 오류 원인 정리

### ISSUE THREAD

**Issue by 753kg** [e-juhee/Shall_we_meet#11]
1. MAIN ISSUE
* 수정 전
desc dates;
MEMBER_ID      --> MEMBERS 테이블의 MEMBER_ID 참조
PLAN_ID            --> PLANS 테이블의 PLAN_ID 참조
SELECT_DATE     --> DATE_OPTIONS 테이블의 HOST_DATE 참조

* 수정 후
desc dates;
MEMBER_ID      --> MEMBERS 테이블의 MEMBER_ID 참조
PLAN_ID            --> **DATE_OPTIONS 테이블**의 PLAN_ID 참조
SELECT_DATE     --> DATE_OPTIONS 테이블의 HOST_DATE 참조

* 이유
DATE_OPTIONS 테이블에서 PLAN_ID와 HOST_DATE 두 개를 묶어서 PK로 정했는데
거기서 HOST_ID만 가져오려고 해서 오류가 났다.
ex)
plan_id      host_date
약속1        10
약속1        12
약속2        10
--> 여기서 10만 가져오면 약속1의 날짜인지 약속2의 날짜인지 알 수 없다

2. DATES테이블의 DATE 컬럼 이름 SELECT_DATE로 수정했습니다. 이름이 조금 헷갈려서요..!!

**Comment by e-juhee** [comment]
나중에 사용하다가 오류가 안 나길 기도해요..ㅎㅎㅠ 고생하셨습니다~~!!
