### ISSUE TITLE
네이버플레이스 액티비티 크롤링 문제

### ISSUE THREAD

**Issue by Youyeon-Kim** [e-juhee/Shall_we_meet#2]
네이버플레이스 크롤링
타 사이트와 같이 html태그로 크롤링 불가능
네이버 API Key 발급받은 후 크롤링 가능함

**Comment by e-juhee** [comment]
카카오 플레이스나 아까 말씀해주신 트립 어드바이저 활용해보는 것도 좋을 것 같아요!!

**Comment by Youyeon-Kim** [comment]
selenium을 이용하여 크롤링에 성공했습니다!
