### ISSUE TITLE
화면 레이아웃

### ISSUE THREAD

**Issue by e-juhee** [e-juhee/Shall_we_meet#24]
금요일에 만든 화면 레이아웃과 참고 링크 업로드 부탁드립니다!

**Comment by Youyeon-Kim** [comment]
https://themewagon.com/themes/free-bootstrap-4-html5-architecture-website-template-arclabs/ 
//템플릿 1
https://themewagon.com/themes/free-bootstrap-4-html5-directory-website-template-citylisting/
//템플릿 2
