### ISSUE TITLE
외부DB접속테스트중입니다

### ISSUE THREAD

**Issue by 753kg** [e-juhee/Shall_we_meet#3]
일단 임시로 DB 계정 이름을 pdbtest로 해봤습니다

사용자이름: pdbtest
비밀번호: pdbtest
호스트이름: 192.168.0.149
포트: 1521
SID: xe

이렇게 접속해서 select 잘 되나 확인 해주세요~
지금 있는 테이블 RESTAURANTS, CAFES 두 개 있습니다

**Comment by e-juhee** [comment]
아주 잘 됩니다!! 👍
