### ISSUE TITLE
다중 날짜 선택

### ISSUE THREAD

**Issue by KimHyunBin0510** [e-juhee/Shall_we_meet#4]
다중 날짜 선택이 가능한 multidatepicker 라이브러리 ex(13 15 17) 을 사용해 봤으나 기본 기능이 한 날짜를 선택할 시에 달력이 사라져 버리는 현상이 발생하여 기간 날짜 식으로 선택 가능한 dateprcker 라이브러리 ex (13~17)를 통해 날짜를 받아 여러번 저장하는 식으로 시도중

**Comment by e-juhee** [comment]
다중 선택이 안된다면 하나씩 선택해서 저장하고 화면에 출력하는 방식으로 진행해도 될 것 같아요.. 일단 다중 선택이 되는 게 가장 깔끔하니 화이팅.... !!!
