### ISSUE TITLE
DB table 제약조건 수정할점 체크

### ISSUE THREAD

**Issue by 753kg** [e-juhee/Shall_we_meet#8]
table_discription.ppt 파일을 보면서 다시 생각을 해봤습니다!!

table_discription_modify.ppt 파일과 DB_todolist.hwp 파일 한번 체크해주세요

제약조건 수정할 테이블 목록

1. PLANS 테이블
 - PLAN_ID 의 FK 빼기 (현재 PK, FK -->  PK )
   * 호스트가 방을 만들면서 친구를 초대할 때 순서가 PLANS에 insert --> members_plans에 insert) 가 된다면 
     FK를 쓸 수 없다. 참조할 수 있는 plan_id가 없게 되기 때문
   * 순서가 (members_plans에 insert --> plans에 insert) 이라면 members_plans의 plan_id가 fk가 되면 안된다.
   * 결론>> 두 테이블 중 하나에서는 fk를 빼야 하니까 plans에서 빼는 게 어떨까요??
 - FIXED DATE NOT NULL 조건 빼기
   * 처음에는 NULL인 상태로 있어야 해서 빼야 할 거 같다.
   * FK조건도 확정된 날짜를 구해서 넣어주는 거라서 빼야 할 것 같습니다!
 - HOTPLACE_NAME도 NOT NULL 조건 빼기. 처음에는 NULL인 상태,

2. DATE_OPTIONS 테이블
 - PLAN_ID, HOST_DATE 합쳐서 복합키로 해야 할 것 같다.
    member_id | host_date
    user1          |  14일
    user1          | 15일
  -> 이렇게 되기 위해서는  PLAN_ID, HOST_DATE를 합쳐야 유일성이 보장됩니다

3. ACTIVITEIS, CAFES, RESTAURANTS 테이블
 - LOCATION_NAME 제약조건 PK, FK (현재 FK --> PK,FK)
    * 지금 CAFES 테이블에서 CAFE_ID가 겹칩니다!! 
    그래서 CAFE_ID와 LOCATION_NAME 합쳐서 복합키로 해야 할 것 같습니다.

**Comment by e-juhee** [comment]
1,2번은 말씀해주신대로 설정하는 게 맞는 것 같아요!!
CAFE_ID는 SEQUENCE로 생성된 데이터라서 중복될 일이 없지 않을까요?!

**Comment by 753kg** [comment]
아 CAFE_NAME이랑 헷갈렸어요!! 그럼 3번은 제외하겠습니다. 감사합니다~
